"""Add group_key to User

Revision ID: 051406a6a597
Revises: cbf34ac935df
Create Date: 2025-05-24 11:27:08.249531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051406a6a597'
down_revision = 'cbf34ac935df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_key', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('group_key')

    # ### end Alembic commands ###
