"""Add icon_filename to User

Revision ID: 247dfcec6f06
Revises: 12ba111b9248
Create Date: 2025-06-18 09:48:25.014353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247dfcec6f06'
down_revision = '12ba111b9248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('icon_filename')

    # ### end Alembic commands ###
