"""Add friendship status and relationships

Revision ID: 2f973910f983
Revises: a3a20ae6cf4e
Create Date: 2025-06-22 18:22:34.962549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f973910f983'
down_revision = 'a3a20ae6cf4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_friend', ['user_id', 'friend_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_friend', type_='unique')

    # ### end Alembic commands ###
