"""Add memo column to UserPhoto

Revision ID: 542910f7b00f
Revises: 
Create Date: 2025-05-12 17:43:25.778330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542910f7b00f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
