"""add want photos and want share flags

Revision ID: 7c9bb8aab298
Revises: 
Create Date: 2026-01-30 22:27:50.376773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9bb8aab298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('want_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('member', sa.String(length=64), nullable=False),
    sa.Column('costume', sa.String(length=128), nullable=False),
    sa.Column('photo_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_key', 'member', 'costume', 'photo_type', name='uq_user_want_photo')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_nogizaka_want_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_sakurazaka_want_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hinatazaka_want_shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_hinatazaka_want_shared')
        batch_op.drop_column('is_sakurazaka_want_shared')
        batch_op.drop_column('is_nogizaka_want_shared')

    op.drop_table('want_photos')
    # ### end Alembic commands ###
