"""Add status column to friendships

Revision ID: a3a20ae6cf4e
Revises: 247dfcec6f06
Create Date: 2025-06-22 11:03:37.159116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a20ae6cf4e'
down_revision = '247dfcec6f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
