"""Initial migration

Revision ID: c2e3a6d79487
Revises: 
Create Date: 2026-04-02 14:05:54.624084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e3a6d79487'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=64), nullable=False),
    sa.Column('costume', sa.String(length=128), nullable=False),
    sa.Column('photo_type', sa.String(length=64), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member', 'costume', 'photo_type', 'group_key', name='_photo_uc')
    )
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.create_index('idx_photo_group', ['group_key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_id', sa.String(length=100), nullable=True),
    sa.Column('public_uuid', sa.String(length=36), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('primary_group', sa.String(length=50), nullable=True),
    sa.Column('selected_groups', sa.String(), nullable=True),
    sa.CheckConstraint("plan_type IN ('free','lite','standard','premium')", name='check_plan_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('user_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=64), nullable=False),
    sa.Column('costume', sa.String(length=128), nullable=False),
    sa.Column('photo_type', sa.String(length=64), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('has_owner', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.CheckConstraint('available_quantity <= quantity'),
    sa.CheckConstraint('available_quantity >= 0'),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'member', 'costume', 'photo_type', 'group', name='_user_photo_uc')
    )
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.create_index('idx_userphoto_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photos_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photos_user_id'), ['user_id'], unique=False)

    op.create_table('want_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('member', sa.String(length=64), nullable=False),
    sa.Column('costume', sa.String(length=128), nullable=False),
    sa.Column('photo_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_key', 'member', 'costume', 'photo_type')
    )
    with op.batch_alter_table('want_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_want_photos_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_want_photos_user_id'), ['user_id'], unique=False)

    op.create_table('want_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.Column('public_uuid', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('user_id', 'group_key')
    )
    with op.batch_alter_table('want_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_want_shares_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('want_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_want_shares_user_id'))

    op.drop_table('want_shares')
    with op.batch_alter_table('want_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_want_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_want_photos_group_key'))

    op.drop_table('want_photos')
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_photos_group_key'))
        batch_op.drop_index('idx_userphoto_user')

    op.drop_table('user_photos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index('idx_photo_group')

    op.drop_table('photo')
    # ### end Alembic commands ###
