"""Add quantity column to UserPhoto

Revision ID: c60b54069b19
Revises: 542910f7b00f
Create Date: 2025-05-12 17:44:54.024060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60b54069b19'
down_revision = '542910f7b00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
