"""Add share settings to User

Revision ID: cbf34ac935df
Revises: 73758640789c
Create Date: 2025-05-21 17:18:48.159524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf34ac935df'
down_revision = '73758640789c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_nogizaka_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_sakurazaka_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hinatazaka_shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_hinatazaka_shared')
        batch_op.drop_column('is_sakurazaka_shared')
        batch_op.drop_column('is_nogizaka_shared')

    # ### end Alembic commands ###
